# - name: Example from an Ansible Playbook
#   ansible.windows.win_ping:
#     data: crash

# - name: Install chocolatey
#   chocolatey_installer: https://chocolatey.org/install.ps1
#   chocolatey_path: c:/ProgramData/chocolatey

- name: Create directory
  ansible.windows.win_file:
    path: C:\Temp
    state: directory

- name: Open port 22
  community.windows.win_firewall_rule:
    name: SSH
    localport: 22
    action: allow
    direction: in
    protocol: tcp
    state: present
    enabled: yes

- name: install the Win32-OpenSSH service
  win_chocolatey:
    name: openssh
    package_params: /SSHServerFeature
    state: present

- name: start SSH service
  win_service:
    name: sshd
    start_mode: auto
    state: started

- name: install wireshark
  win_chocolatey:
    name: wireshark
    state: present
    package_params:
      - /S
      - /NCRC
      - /desktopicon=yes
      - /quicklaunchicon=yes

- name: install libroffice
  win_chocolatey:
    name: libreoffice
    state: present
