---
- name: Installer Apache & PHP Debian
  ansible.builtin.apt:
    name: "{{item}}"
    state: present
  loop:
    - apache2
    - libapache2-mod-php7.4
  when: ansible_facts['os_family'] == "Debian"

- name: Installer Apache
  ansible.builtin.yum:
    name: httpd
    state: present
    update_cache: true
  when: ansible_facts['os_family'] == "Redhat"


- name: Démarrer le service Apache Debian
  ansible.builtin.service:
    name: apache2
    state: started
    enabled: true
  when: ansible_facts['os_family'] == "Debian"

- name: Démarrer le service Apache
  ansible.builtin.service:
    name: httpd
    state: started
    enabled: true
  when: ansible_facts['os_family'] == "Redhat"


- name: copier un phpinfo
  ansible.builtin.copy:
    src: info.php
    dest: /var/www/html/index.php
    owner: www-data
    group: www-data
    mode: 0664
  when: ansible_facts['os_family'] == "Debian"

- name: copier un phpinfo
  ansible.builtin.copy:
    src: info.php
    dest: /var/www/html/index.php
    owner: apache
    group: apache
    mode: 0664
  when: ansible_facts['os_family'] == "Redhat"

- name: copier ports
  template:
    src: ports.j2
    dest: /etc/apache2/ports.conf
    owner: www-data
    group: www-data
    mode: 0664
  notify: Restart apache
  when: ansible_facts['os_family'] == "Debian"
